FROM openjdk
WORKDIR /usr/lib
ADD ./target/Authentication-Application-0.0.1-SNAPSHOT.jar /usr/lib/Authentication-Application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Authentication-Application-0.0.1-SNAPSHOT.jar"]