FROM openjdk
WORKDIR /usr/lib
ADD ./target/EmployeeNotification-0.0.1-SNAPSHOT.jar /usr/lib/EmployeeNotification-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","EmployeeNotification-0.0.1-SNAPSHOT.jar"]